# Generated by Django 5.1.6 on 2025-02-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0002_category_likes_category_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
